### ISSUE TITLE
Criação do RestController para listar clientes no EndPoint do serviço Cliente Service

### ISSUE THREAD

**Issue by LuizHenriqueT1** [LuizHenriqueT1/helpr-1#1]

**Comment by LuizHenriqueT1** [comment]
- [ ] Criar Controller Rest

- [ ] Criar Serviço de Cliente 

- [ ] Criar métodos para EndPoint de RestController

- [ ] Vincular os repositórios de cliente

- [ ] Testar Endpoint

**Comment by LuizHenriqueT1** [comment]
452acc97cd43c1e339f93e780fe8b49c51a0f1b0

**Comment by soulcode-acad** [comment]
Alguns pontos Luiz devem ser observados que seu backlog ficou meio desorganizado e que algumas tarefas não tem anexo de entrega como essa aqui, o código tinha alguns defeitos nomenclatura, mas de de resto foi tudo bem.
![image](https://user-images.githubusercontent.com/100297907/172861078-f2a843b0-260e-44ef-a375-bf6f4bf3dd40.png)
